# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "debian/bullseye64"
  config.vm.box_version = "11.20230615.1"
  config.vm.hostname = "DockerCompose"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "compose.sh"
end
